name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@derpierre65'
      - run: |
          cd packages/vue3-drr-grid-layout
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Assets
          path: ./packages/vue3-drr-grid-layout/dist